# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180316_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, default='', upload_to='item_image'),
        ),
    ]
