# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='content',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='producer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product_details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, default='', upload_to='item_images'),
        ),
    ]
