# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180319_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='/category_images/missing-image.png', upload_to='category_images'),
        ),
    ]
